# Generated by Django 4.1.5 on 2023-01-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=32)),
                ("city", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=128)),
                ("phone_num", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("personal_email", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=6,
                    ),
                ),
                ("birth_date", models.DateField()),
            ],
            options={
                "db_table": "persons",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=128)),
                ("is_current_job", models.BooleanField()),
                ("company_email", models.CharField(max_length=50)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees_app.company",
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees_app.person",
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="persons",
            field=models.ManyToManyField(
                through="employees_app.Employee", to="employees_app.person"
            ),
        ),
    ]
