# Generated by Django 4.1.5 on 2023-01-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Polygender", "Polygender"),
                    ("Genderfluid", "Genderfluid"),
                    ("Bigender", "Bigender"),
                    ("Agender", "Agender"),
                ],
                max_length=16,
            ),
        ),
    ]
