# Generated by Django 4.1.5 on 2023-03-11 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight_number", models.SmallIntegerField(unique=True)),
                ("origin_city", models.CharField(max_length=128)),
                ("destination_city", models.CharField(max_length=128)),
                ("origin_airport_code", models.CharField(max_length=3)),
                ("destination_airport_code", models.CharField(max_length=3)),
                ("date_time_origin", models.DateTimeField()),
                ("date_time_destination", models.DateTimeField()),
                ("total_num_seats", models.SmallIntegerField()),
                ("seats_left", models.SmallIntegerField()),
                ("is_cancelled", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                "db_table": "flights",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("number_of_seats", models.SmallIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="api.flight"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "orders",
            },
        ),
    ]
