# Generated by Django 4.1.5 on 2023-01-18 19:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=256)),
                ("description", models.TextField(db_column="description")),
                ("duration_in_mins", models.FloatField(db_column="duration")),
                (
                    "release_year",
                    models.SmallIntegerField(
                        db_column="year",
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2050),
                        ],
                    ),
                ),
                (
                    "pic_url",
                    models.URLField(db_column="poster_url", max_length=512, null=True),
                ),
            ],
            options={
                "db_table": "movies",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_text", models.TextField(db_column="review_text")),
                ("review_date", models.DateField(db_column="review_date")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="movies_app.movie",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        db_column="rating",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                ("rating_date", models.DateField(db_column="rating_date")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="movies_app.movie",
                    ),
                ),
            ],
            options={
                "db_table": "ratings",
            },
        ),
    ]
